### ISSUE TITLE
jammy_cli_b27 never reach the login prompt using CM3 + CM3 I/O

### ISSUE THREAD

**Issue by Sfinx** [radxa-build/radxa-cm3-io#4] opened 2024-02-15 05:40 UTC
No network, no ssh access too, log:

```
U-Boot latest-2023.10-8-eed05a18-geed05a18 (Jan 10 2024 - 03:33:21 +0000)

Model: Radxa Compute Module 3(CM3) IO Board
DRAM:  1 GiB (effective 1022 MiB)
PMIC:  RK8170 (on=0x40, off=0x00)
Core:  325 devices, 29 uclasses, devicetree: separate
MMC:   mmc@fe2b0000: 1, mmc@fe2c0000: 2, mmc@fe310000: 0
Loading Environment from nowhere... OK
In:    serial@fe660000
Out:   serial@fe660000
Err:   serial@fe660000
Model: Radxa Compute Module 3(CM3) IO Board
Net:   No ethernet found.
starting USB...
Bus usb@fcc00000: Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
Bus usb@fd000000: Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
Bus usb@fd800000: USB EHCI 1.00
scanning bus usb@fcc00000 for devices... 1 USB Device(s) found
scanning bus usb@fd000000 for devices... 1 USB Device(s) found
scanning bus usb@fd800000 for devices... 2 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
pcie_dw_rockchip pcie@fe260000: PCIe-0 Link Fail
Hit Ctrl+C key in 0 seconds to stop autoboot...
Card did not respond to voltage select! : -110
** Booting bootflow 'mmc@fe310000.bootdev.part_3' with extlinux
U-Boot menu
1:	Ubuntu 22.04.3 LTS 5.10.160-26-rk356x
2:	Ubuntu 22.04.3 LTS 5.10.160-26-rk356x (rescue target)
Enter choice: 1:	Ubuntu 22.04.3 LTS 5.10.160-26-rk356x
Retrieving file: /boot/vmlinuz-5.10.160-26-rk356x
Retrieving file: /boot/initrd.img-5.10.160-26-rk356x
append: root=UUID=1a868455-fef3-45c0-8fe9-7a6134184750 console=ttyFIQ0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
Moving Image from 0x2080000 to 0x2200000, end=3d80000
## Flattened Device Tree blob at 3debff10
   Booting using the fdt blob at 0x3debff10
Working FDT set to 3debff10
Host not halted after 16000 microseconds.
   Loading Ramdisk to 3c488000, end 3ceb2095 ... OK
   Loading Device Tree to 000000003c472000, end 000000003c487e6f ... OK
Working FDT set to 3c472000

Starting kernel ...

[    8.555632] rockchip_clk_register_muxgrf: regmap not available
[    8.556204] rockchip_clk_register_branches: failed to register clock clk_32k_ioe: -524
```

**Comment by Sfinx** [comment] 2024-02-15 06:41
Checked, old focal server image boots ok:

https://github.com/radxa/debos-radxa/releases/download/20230201-0944/radxa-cm3-io-ubuntu-focal-server-arm64-20230201-1058-gpt.img.xz

**Comment by Sfinx** [comment] 2024-02-15 07:03
jammy b25 boots ok too. jammy b26 hangs. Seems like regression is between b25 and b26

**Comment by Sfinx** [comment] 2024-02-15 07:13
debian_bullseye_xfce_b27 boots ok. So the bug is affecting cli version only

**Comment by RadxaYuntian** [comment] 2024-02-18 09:16
Duplicate of #5 
Plus Ubuntu is not a supported system. It is provided AS-IS.

**Closed by RadxaYuntian** 2024-02-18 09:16 UTC
